'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const context={window:{},queueMicrotask};vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(__dirname,'../src/ui/preferences.js'),'utf8'),context);
const tick=()=>new Promise(r=>setImmediate(r));const results=[];
async function check(name,run){await run();results.push({name,passed:true});}
function fixture(initial={a:false,b:false}){const state={...initial},writes=[],errors=[],renders=[];let settled=0;const writer=context.window.NXPreferences.create({read:k=>state[k],project:(k,v,target=state)=>target[k]=v,write:(k,v)=>new Promise((resolve,reject)=>writes.push({k,v,resolve,reject})),changed:()=>renders.push({...state}),failed:e=>errors.push(e.message),settled:()=>settled++});return {state,writes,errors,renders,writer,get settled(){return settled}};}
(async()=>{
 await check('click/changes-state-synchronously',()=>{const f=fixture();f.writer.set('a',true);assert.equal(f.state.a,true);assert.equal(f.writes.length,0);assert.equal(f.renders.length,1);});
 await check('click/rapid-double-click-is-last-intent',async()=>{const f=fixture();f.writer.set('a',true);f.writer.set('a',false);await tick();assert.equal(f.writes.length,1);assert.equal(f.writes[0].v,false);f.writes[0].resolve({ok:true});await tick();assert.equal(f.state.a,false);assert.equal(f.writer.pending(),false);});
 await check('queue/inflight-write-serializes-newer-choice',async()=>{const f=fixture();f.writer.set('a',true);await tick();f.writer.set('a',false);assert.equal(f.state.a,false);assert.equal(f.writes.length,1);f.writes[0].resolve({ok:true});await tick();assert.equal(f.writes.length,2);assert.equal(f.state.a,false);f.writes[1].resolve({ok:true});await tick();assert.equal(f.writer.pending(),false);});
 await check('rollback/latest-failure-only',async()=>{const f=fixture();f.writer.set('a',true);await tick();f.writes[0].reject(new Error('disk'));await tick();assert.equal(f.state.a,false);assert.deepEqual(f.errors,['disk']);});
 await check('rollback/superseded-failure-does-not-flash-error',async()=>{const f=fixture();f.writer.set('a',true);await tick();f.writer.set('a',false);f.writes[0].reject(new Error('old'));await tick();assert.equal(f.state.a,false);assert.deepEqual(f.errors,[]);f.writes[1].resolve({ok:true});await tick();});
 await check('rollback/restores-last-acknowledged-not-initial',async()=>{const f=fixture();f.writer.set('a',true);await tick();f.writer.set('a',false);f.writes[0].resolve({ok:true});await tick();f.writes[1].reject(new Error('second'));await tick();assert.equal(f.state.a,true);});
 await check('read/late-snapshot-cannot-undo-inflight',async()=>{const f=fixture(),ticket=f.writer.readTicket();f.writer.set('a',true);const stale={a:false,b:true};f.writer.reconcile(stale,ticket);assert.deepEqual(stale,{a:true,b:true});});
 await check('read/started-before-ack-cannot-retire-overlay',async()=>{const f=fixture();f.writer.set('a',true);await tick();const t=f.writer.readTicket();f.writes[0].resolve({ok:true});await tick();const stale={a:false};f.writer.reconcile(stale,t);assert.equal(stale.a,true);});
 await check('read/fresh-post-ack-allows-authoritative-external-change',async()=>{const f=fixture();f.writer.set('a',true);await tick();f.writes[0].resolve({ok:true});await tick();const t=f.writer.readTicket(),fresh={a:false};f.writer.reconcile(fresh,t);assert.equal(fresh.a,false);});
 await check('read/old-settled-ticket-cannot-retire-new-click',async()=>{const f=fixture();f.writer.set('a',true);await tick();f.writes[0].resolve({ok:true});await tick();const t=f.writer.readTicket();f.writer.set('a',false);const old={a:true};f.writer.reconcile(old,t);assert.equal(old.a,false);});
 await check('accounts/separate-keys-avoid-lost-exclusions',async()=>{const f=fixture({'account:one':true,'account:two':true});f.writer.set('account:one',false);f.writer.set('account:two',false);await tick();assert.equal(f.writes[0].k,'account:one');f.writes[0].resolve({ok:true});await tick();assert.equal(f.writes[1].k,'account:two');f.writes[1].resolve({ok:true});await tick();assert.deepEqual(f.state,{'account:one':false,'account:two':false});});
 await check('failure/returned-ok-false-rolls-back',async()=>{const f=fixture();f.writer.set('a',true);await tick();f.writes[0].resolve({ok:false,error:'denied'});await tick();assert.equal(f.state.a,false);assert.deepEqual(f.errors,['denied']);});
 console.log(JSON.stringify(results,null,2));
})().catch(e=>{console.error(e.stack);process.exitCode=1;});
