"""Regression cases for maintained product flows; removed compact/manual-message UI retired in 5.7.5."""
from __future__ import annotations
import argparse,json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT/'tools'))
from browser_session import browser_session,demo_html

CASES = [
('root/three-groups-no-submenu-links', 'open=settings', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));const input=(id,v)=>{const n=$('#'+id);n.value=v;n.dispatchEvent(new Event('input',{bubbles:true}));return n;};return [...document.querySelectorAll('.settings-heading')].map(n=>n.textContent).join('|')==='系统|接力与接续|账号'&&!$('#sheet [data-action=automation]')&&!$('#sheet [data-action=notifications]');}'''),
('root/default-fixed-width-scrollable', 'open=settings', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));const input=(id,v)=>{const n=$('#'+id);n.value=v;n.dispatchEvent(new Event('input',{bubbles:true}));return n;};const b=$('.sheet-body');return b.scrollWidth===b.clientWidth&&NXPreview.info().width===372&&NXPreview.info().height===520;}'''),
('root/notifications-in-system', 'open=settings', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));const input=(id,v)=>{const n=$('#'+id);n.value=v;n.dispatchEvent(new Event('input',{bubbles:true}));return n;};const d=$('[data-disclosure=notifications]');d.querySelector('summary').click();await sleep(25);return d.open&&d.closest('.settings-section').querySelector('h3').textContent==='系统'&&NXPreview.info().page==='settings';}'''),
('root/all-old-settings-links-resolve-inline', 'open=settings', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));const input=(id,v)=>{const n=$('#'+id);n.value=v;n.dispatchEvent(new Event('input',{bubbles:true}));return n;};for(const route of ['automation','notifications','relay-accounts','resume-message','hotkeys','archives']){await NXPreview.open(new URLSearchParams('open='+route));if(NXPreview.info().page!=='settings')return false;}return true;}'''),
('root/expansion-keeps-width-and-frame', 'open=settings', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));const input=(id,v)=>{const n=$('#'+id);n.value=v;n.dispatchEvent(new Event('input',{bubbles:true}));return n;};const b=$('.sheet-body'),w=b.clientWidth;for(const key of ['appearance','notifications','relay','message','hotkeys','archives']){$('[data-disclosure='+key+'] summary').click();await sleep(30);}return $('.sheet-body').clientWidth===w&&NXPreview.info().height===520&&$('.sheet-body').scrollHeight>$('.sheet-body').clientHeight;}'''),
('relay/dense-identity-only', 'open=relay-accounts', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));const input=(id,v)=>{const n=$('#'+id);n.value=v;n.dispatchEvent(new Event('input',{bubbles:true}));return n;};const rows=[...document.querySelectorAll('.relay-account-row')];return rows.length===5&&rows.every(r=>r.offsetHeight===42&&r.querySelector('.relay-account-name')&&r.querySelector('.badge')&&r.querySelector('.switch')&&!r.querySelector('.avatar,.choice-quotas,.current-chip,[data-action=detail]'));}'''),
('relay/long-names-cannot-hide-plan', 'open=relay-accounts&scenario=long-names', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));const input=(id,v)=>{const n=$('#'+id);n.value=v;n.dispatchEvent(new Event('input',{bubbles:true}));return n;};return [...document.querySelectorAll('.relay-account-row')].every(r=>{const n=r.querySelector('.relay-account-name'),p=r.querySelector('.badge').getBoundingClientRect(),s=r.querySelector('.switch').getBoundingClientRect();return n.scrollWidth>=n.clientWidth&&n.getBoundingClientRect().right<=p.left&&p.right<s.left&&s.right<=r.getBoundingClientRect().right;});}'''),
('relay/long-list-eight-then-rest', 'open=relay-accounts&scenario=many', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));const input=(id,v)=>{const n=$('#'+id);n.value=v;n.dispatchEvent(new Event('input',{bubbles:true}));return n;};if(document.querySelectorAll('.relay-account-row').length!==8)return false;$('[data-action=collection-more][data-value=relay]').click();return document.querySelectorAll('.relay-account-row').length===14&&NXPreview.info().page==='settings';}'''),
('relay/immediate-repeat-click', 'open=relay-accounts&scenario=preference-pending', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));const input=(id,v)=>{const n=$('#'+id);n.value=v;n.dispatchEvent(new Event('input',{bubbles:true}));return n;};const sel='.relay-account-row .switch',before=$(sel).getAttribute('aria-checked');$(sel).click();if($(sel).getAttribute('aria-checked')===before||$(sel).disabled)return false;$(sel).click();return $(sel).getAttribute('aria-checked')===before&&!$(sel).disabled;}'''),
('roster/home-other-accounts-still-have-quotas', '', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));const input=(id,v)=>{const n=$('#'+id);n.value=v;n.dispatchEvent(new Event('input',{bubbles:true}));return n;};return [...document.querySelectorAll('.account-list .row')].every(r=>!!r.querySelector('.roster-quotas'));}'''),
('empty/message-centered-in-all-remaining-space', 'scenario=single-account', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));const input=(id,v)=>{const n=$('#'+id);n.value=v;n.dispatchEvent(new Event('input',{bubbles:true}));return n;};const n=$('.roster-empty'),p=n.parentElement.getBoundingClientRect(),r=n.firstElementChild.getBoundingClientRect();return Math.abs((r.top+r.bottom-p.top-p.bottom)/2)<1&&Math.abs((r.left+r.right-p.left-p.right)/2)<1;}'''),
('empty/no-empty-message-with-other-accounts', '', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));const input=(id,v)=>{const n=$('#'+id);n.value=v;n.dispatchEvent(new Event('input',{bubbles:true}));return n;};return !$('.roster-empty')&&document.querySelectorAll('.account-list .row').length>0;}'''),
('message/one-line-with-square-check', 'open=resume-message', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));const input=(id,v)=>{const n=$('#'+id);n.value=v;n.dispatchEvent(new Event('input',{bubbles:true}));return n;};const f=$('#resume-message'),b=$('[data-action=save-resume-message]'),a=f.getBoundingClientRect(),c=b.getBoundingClientRect();return f.tagName==='INPUT'&&f.type==='text'&&c.width===c.height&&Math.abs(c.top-a.top)<.5&&a.height===c.height&&!b.textContent.trim()&&b.getAttribute('aria-label')==='保存接续消息';}'''),
('message/save-without-navigation', 'open=resume-message', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));const input=(id,v)=>{const n=$('#'+id);n.value=v;n.dispatchEvent(new Event('input',{bubbles:true}));return n;};input('resume-message','继续核对');$('[data-action=save-resume-message]').click();await sleep(90);return NXPreview.info().page==='settings'&&NXDemo.state().settings.resume_message==='继续核对'&&$('[data-disclosure=message]').open&&!$('.status-notification');}'''),
('message/empty-validation-is-local', 'open=resume-message', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));const input=(id,v)=>{const n=$('#'+id);n.value=v;n.dispatchEvent(new Event('input',{bubbles:true}));return n;};input('resume-message','');$('[data-action=save-resume-message]').click();await sleep(20);return !!$('#form-error').textContent&&$('#resume-message').getAttribute('aria-invalid')==='true'&&NXDemo.state().settings.resume_message==='继续';}'''),
('message/failure-preserves-input', 'open=resume-message&scenario=preference-failed', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));const input=(id,v)=>{const n=$('#'+id);n.value=v;n.dispatchEvent(new Event('input',{bubbles:true}));return n;};input('resume-message','不丢失的消息');$('[data-action=save-resume-message]').click();await sleep(80);await NXPreview.refresh();return $('#resume-message').value==='不丢失的消息'&&!!$('#form-error').textContent&&!$('[data-action=save-resume-message]').disabled;}'''),
('message/switches-and-collapse-preserve-draft', 'open=resume-message', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));const input=(id,v)=>{const n=$('#'+id);n.value=v;n.dispatchEvent(new Event('input',{bubbles:true}));return n;};const field=input('resume-message','尚未保存');$('[data-key=auto_relay]').click();await sleep(30);if($('#resume-message')!==field)return false;$('[data-disclosure=message] summary').click();await sleep(15);$('[data-disclosure=message] summary').click();await sleep(15);return $('#resume-message').value==='尚未保存';}'''),
('message/late-result-does-not-consume-new-input', 'open=resume-message', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));const input=(id,v)=>{const n=$('#'+id);n.value=v;n.dispatchEvent(new Event('input',{bubbles:true}));return n;};const real=NXDemo.call;let release;NXDemo.call=(m,...a)=>m==='set_preferences'?new Promise(r=>release=()=>real(m,...a).then(r)):real(m,...a);input('resume-message','第一条');$('[data-action=save-resume-message]').click();input('resume-message','新的未保存内容');release();await sleep(90);return $('#resume-message').value==='新的未保存内容'&&NXDemo.state().settings.resume_message==='第一条';}'''),
('message/enter-saves-without-adding-line', 'open=resume-message', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));const input=(id,v)=>{const n=$('#'+id);n.value=v;n.dispatchEvent(new Event('input',{bubbles:true}));return n;};const f=input('resume-message','键盘保存');f.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}));await sleep(60);return NXDemo.state().settings.resume_message==='键盘保存';}'''),
('meta/inline-not-a-subpage', 'open=detail', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));const input=(id,v)=>{const n=$('#'+id);n.value=v;n.dispatchEvent(new Event('input',{bubbles:true}));return n;};$('.account-editor summary').click();await sleep(20);return NXPreview.info().page==='detail'&&$('.account-editor summary').textContent.includes('昵称与会员期限')&&!!$('#alias')&&!!$('#manual-date');}'''),
('meta/legacy-deep-link-opens-same-detail', 'open=edit', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));const input=(id,v)=>{const n=$('#'+id);n.value=v;n.dispatchEvent(new Event('input',{bubbles:true}));return n;};return NXPreview.info().page==='detail'&&$('.account-editor details').open;}'''),
('meta/two-equal-width-inputs-checks', 'open=edit', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));const input=(id,v)=>{const n=$('#'+id);n.value=v;n.dispatchEvent(new Event('input',{bubbles:true}));return n;};const rows=[...document.querySelectorAll('.account-editor .inline-field')];return rows.length===2&&rows[0].querySelector('input').getBoundingClientRect().width===rows[1].querySelector('input').getBoundingClientRect().width&&rows.every(r=>r.querySelector('button').offsetWidth===32&&r.querySelector('input').offsetHeight===32);}'''),
('meta/alias-save-preserves-date', 'open=edit&scenario=membership-manual', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));const input=(id,v)=>{const n=$('#'+id);n.value=v;n.dispatchEvent(new Event('input',{bubbles:true}));return n;};const date=NXDemo.state().accounts[0].manual_subscription_date;input('alias','新昵称');$('[data-action=save-alias]').click();await sleep(75);return NXDemo.state().accounts[0].alias==='新昵称'&&NXDemo.state().accounts[0].manual_subscription_date===date&&NXPreview.info().page==='detail'&&$('.account-editor details').open;}'''),
('meta/alias-save-does-not-save-dirty-date', 'open=edit', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));const input=(id,v)=>{const n=$('#'+id);n.value=v;n.dispatchEvent(new Event('input',{bubbles:true}));return n;};input('alias','保存昵称');input('manual-date','2027-11-22');$('[data-action=save-alias]').click();await sleep(75);return !NXDemo.state().accounts[0].manual_subscription_date&&$('#manual-date').value==='2027-11-22';}'''),
('meta/date-save-does-not-save-dirty-alias', 'open=edit', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));const input=(id,v)=>{const n=$('#'+id);n.value=v;n.dispatchEvent(new Event('input',{bubbles:true}));return n;};const alias=NXDemo.state().accounts[0].alias;input('alias','未保存昵称');input('manual-date','2027-11-22');$('[data-action=save-expiry]').click();await sleep(75);return NXDemo.state().accounts[0].alias===alias&&$('#alias').value==='未保存昵称'&&NXDemo.state().accounts[0].manual_subscription_date==='2027-11-22';}'''),
('meta/two-independent-writes-merge', 'open=edit', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));const input=(id,v)=>{const n=$('#'+id);n.value=v;n.dispatchEvent(new Event('input',{bubbles:true}));return n;};input('alias','合并');input('manual-date','2027-11-22');$('[data-action=save-alias]').click();$('[data-action=save-expiry]').click();await sleep(90);const a=NXDemo.state().accounts[0];return a.alias==='合并'&&a.manual_subscription_date==='2027-11-22';}'''),
('meta/late-save-preserves-new-nickname', 'open=edit', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));const input=(id,v)=>{const n=$('#'+id);n.value=v;n.dispatchEvent(new Event('input',{bubbles:true}));return n;};const real=NXDemo.call;let release;NXDemo.call=(m,...a)=>m==='update_account_meta'?new Promise(r=>release=()=>real(m,...a).then(r)):real(m,...a);input('alias','提交的名字');$('[data-action=save-alias]').click();input('alias','新的名字');release();await sleep(90);return $('#alias').value==='新的名字'&&NXDemo.state().accounts[0].alias==='提交的名字';}'''),
('meta/duplicate-click-on-pending-does-not-write-twice', 'open=edit', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));const input=(id,v)=>{const n=$('#'+id);n.value=v;n.dispatchEvent(new Event('input',{bubbles:true}));return n;};const real=NXDemo.call;let count=0,release;NXDemo.call=(m,...a)=>m==='update_account_meta'?(count++,new Promise(r=>release=()=>real(m,...a).then(r))):real(m,...a);input('alias','只有一次');$('[data-action=save-alias]').click();$('[data-action=save-alias]').click();const busy=$('[data-action=save-alias]').disabled;release();await sleep(80);return count===1&&busy;}'''),
('meta/save-error-keeps-both-fields', 'open=edit&scenario=save-failed', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));const input=(id,v)=>{const n=$('#'+id);n.value=v;n.dispatchEvent(new Event('input',{bubbles:true}));return n;};const f=input('alias','未保存昵称'),d=input('manual-date','2027-11-22');$('[data-action=save-alias]').click();await sleep(75);return $('#alias')===f&&$('#manual-date')===d&&f.value==='未保存昵称'&&d.value==='2027-11-22'&&!!$('#form-error').textContent;}'''),
('meta/refresh-keeps-field-caret-and-focus', 'open=edit', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));const input=(id,v)=>{const n=$('#'+id);n.value=v;n.dispatchEvent(new Event('input',{bubbles:true}));return n;};const f=input('alias','持续输入的昵称');f.focus();f.setSelectionRange(2,4);await NXPreview.refresh();return $('#alias')===f&&document.activeElement===f&&f.selectionStart===2&&f.selectionEnd===4;}'''),
('meta/composition-not-replaced-or-saved', 'open=edit', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));const input=(id,v)=>{const n=$('#'+id);n.value=v;n.dispatchEvent(new Event('input',{bubbles:true}));return n;};const real=NXDemo.call;let calls=0;NXDemo.call=(m,...a)=>{if(m==='update_account_meta')calls++;return real(m,...a);};const f=input('alias','输入法组合');f.focus();f.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));const summary=$('.account-editor summary');await NXDemo.call('set_preferences',{auto_relay:true});await NXPreview.refresh();if($('.account-editor summary')!==summary)return false;f.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',isComposing:true,bubbles:true}));f.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true}));await sleep(30);return calls===0&&$('#alias')===f&&f.value==='输入法组合';}'''),
('meta/collapse-and-reopen-preserves-unsaved-values', 'open=edit', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));const input=(id,v)=>{const n=$('#'+id);n.value=v;n.dispatchEvent(new Event('input',{bubbles:true}));return n;};input('alias','保留草稿');input('manual-date','2027-11-22');$('.account-editor summary').click();await sleep(20);await NXPreview.refresh();$('.account-editor summary').click();await sleep(20);return $('#alias').value==='保留草稿'&&$('#manual-date').value==='2027-11-22';}'''),
('meta/date-save-collapse-keeps-action-position', 'open=detail&scenario=member-none', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));const input=(id,v)=>{const n=$('#'+id);n.value=v;n.dispatchEvent(new Event('input',{bubbles:true}));return n;};const y=$('.danger-row').getBoundingClientRect().top;$('.account-editor summary').click();await sleep(15);input('manual-date','2027-11-22');$('[data-action=save-expiry]').click();await sleep(70);$('.account-editor summary').click();await sleep(15);return $('.danger-row').getBoundingClientRect().top===y&&$('.detail-expiry-note').textContent.includes('2027/11/22');}'''),
('meta/late-save-cannot-cross-account', 'open=edit', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));const input=(id,v)=>{const n=$('#'+id);n.value=v;n.dispatchEvent(new Event('input',{bubbles:true}));return n;};const real=NXDemo.call;let release;NXDemo.call=(m,...a)=>m==='update_account_meta'?new Promise(r=>release=()=>real(m,...a).then(r)):real(m,...a);input('alias','第一个账号');$('[data-action=save-alias]').click();await NXPreview.open(new URLSearchParams('open=edit&email=backup@example.com'));input('alias','第二个账号未保存');release();await sleep(90);return $('#alias').value==='第二个账号未保存'&&NXPreview.info().page==='detail'&&NXDemo.state().accounts[1].alias!=='第一个账号';}'''),
('meta/clear-date-keeps-fixed-note', 'open=edit&scenario=membership-manual', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));const input=(id,v)=>{const n=$('#'+id);n.value=v;n.dispatchEvent(new Event('input',{bubbles:true}));return n;};input('manual-date','');$('[data-action=save-expiry]').click();await sleep(75);return NXDemo.state().accounts[0].manual_subscription_date===null&&$('.detail-expiry-note').offsetHeight===20;}'''),
('meta/credits-remains-visible', 'open=detail&scenario=credits-zero', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));const input=(id,v)=>{const n=$('#'+id);n.value=v;n.dispatchEvent(new Event('input',{bubbles:true}));return n;};return $('.detail-compact').textContent.includes('Credits0.00');}'''),
('meta/immediate-expand-save-does-not-recollapse', 'open=detail', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));const input=(id,v)=>{const n=$('#'+id);n.value=v;n.dispatchEvent(new Event('input',{bubbles:true}));return n;};$('.account-editor summary').click();input('alias','立即保存');$('[data-action=save-alias]').click();await sleep(80);return $('.account-editor details').open&&$('#alias').value==='立即保存';}'''),
('meta/committed-save-unlocks-before-slow-observation', 'open=edit', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));const input=(id,v)=>{const n=$('#'+id);n.value=v;n.dispatchEvent(new Event('input',{bubbles:true}));return n;};const real=NXDemo.call;let release,writes=0,reads=0;NXDemo.call=(m,...a)=>{if(m==='get_data'&&++reads===1)return new Promise(r=>release=()=>real(m,...a).then(r));if(m==='update_account_meta')writes++;return real(m,...a);};input('alias','第一稿');$('[data-action=save-alias]').click();await sleep(35);if($('[data-action=save-alias]').disabled)return false;input('alias','第二稿');$('[data-action=save-alias]').click();await sleep(35);if(writes!==2||!release)return false;release();await sleep(70);return NXDemo.state().accounts[0].alias==='第二稿'&&$('#alias').value==='第二稿';}'''),
('message/old-multiline-keeps-word-boundaries-without-autosave', '', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));const input=(id,v)=>{const n=$('#'+id);n.value=v;n.dispatchEvent(new Event('input',{bubbles:true}));return n;};const real=NXDemo.call;let writes=0;NXDemo.call=async(m,...a)=>{if(m==='set_preferences')writes++;const r=await real(m,...a);if(m==='get_data')r.settings.resume_message='继续\n核对';return r;};await NXPreview.open(new URLSearchParams('open=resume-message'));return $('#resume-message').value==='继续 核对'&&writes===0;}'''),
]

def main(browser,output):
    results=[]
    with browser_session(browser) as engine:
        for palette in ['light','dark']:
            for name,q,script in CASES:
                ctx=engine.new_context(viewport={'width':520,'height':700},color_scheme=palette,reduced_motion='reduce');p=ctx.new_page();errors=[];p.on('pageerror',lambda e:errors.append(str(e)))
                try:
                    p.set_content(demo_html(q+'&appearance='+palette));p.wait_for_function('window.NX_CASE_READY',timeout=6000);passed=p.evaluate(script) is True
                except Exception as e:errors.append(str(e));passed=False
                results.append({'name':name,'appearance':palette,'passed':passed and not errors,'errors':errors});ctx.close()
    output.parent.mkdir(parents=True,exist_ok=True);output.write_text(json.dumps(results,ensure_ascii=False,indent=2));print('Inline UX:',sum(r['passed'] for r in results),'/',len(results))
    for r in results:
        if not r['passed']:print(r)
    return int(any(not r['passed'] for r in results))
if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--browser',required=True,type=Path);p.add_argument('--output',type=Path,default=ROOT/'docs/validation/ui-inline-tests.json');a=p.parse_args();raise SystemExit(main(a.browser,a.output))
