"""Regression cases for maintained product flows; removed compact/manual-message UI retired in 5.7.5."""
from __future__ import annotations
import argparse,json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT/'tools'))
from browser_session import browser_session,demo_html

CASES = [
('switch/autostart-immediate-and-reversible', 'open=settings', r'''()=>{const sel='[data-key="autostart"][role="switch"]',real=NXDemo.call;NXDemo.call=(m,...a)=>m==='set_preferences'?new Promise(()=>{}):real(m,...a);const before=document.querySelector(sel).getAttribute('aria-checked');document.querySelector(sel).click();const now=document.querySelector(sel),one=now.getAttribute('aria-checked')!==before&&!now.disabled&&!now.hasAttribute('aria-busy');now.click();return one&&document.querySelector(sel).getAttribute('aria-checked')===before&&!document.querySelector(sel).querySelector('.control-feedback');}'''),
('switch/auto_relay-immediate-and-reversible', 'open=automation', r'''()=>{const sel='[data-key="auto_relay"][role="switch"]',real=NXDemo.call;NXDemo.call=(m,...a)=>m==='set_preferences'?new Promise(()=>{}):real(m,...a);const before=document.querySelector(sel).getAttribute('aria-checked');document.querySelector(sel).click();const now=document.querySelector(sel),one=now.getAttribute('aria-checked')!==before&&!now.disabled&&!now.hasAttribute('aria-busy');now.click();return one&&document.querySelector(sel).getAttribute('aria-checked')===before&&!document.querySelector(sel).querySelector('.control-feedback');}'''),
('switch/task_continuation-immediate-and-reversible', 'open=automation', r'''()=>{const sel='[data-key="task_continuation"][role="switch"]',real=NXDemo.call;NXDemo.call=(m,...a)=>m==='set_preferences'?new Promise(()=>{}):real(m,...a);const before=document.querySelector(sel).getAttribute('aria-checked');document.querySelector(sel).click();const now=document.querySelector(sel),one=now.getAttribute('aria-checked')!==before&&!now.disabled&&!now.hasAttribute('aria-busy');now.click();return one&&document.querySelector(sel).getAttribute('aria-checked')===before&&!document.querySelector(sel).querySelector('.control-feedback');}'''),
('switch/notify_credential-immediate-and-reversible', 'open=notifications', r'''()=>{const sel='[data-key="notify_credential"][role="switch"]',real=NXDemo.call;NXDemo.call=(m,...a)=>m==='set_preferences'?new Promise(()=>{}):real(m,...a);const before=document.querySelector(sel).getAttribute('aria-checked');document.querySelector(sel).click();const now=document.querySelector(sel),one=now.getAttribute('aria-checked')!==before&&!now.disabled&&!now.hasAttribute('aria-busy');now.click();return one&&document.querySelector(sel).getAttribute('aria-checked')===before&&!document.querySelector(sel).querySelector('.control-feedback');}'''),
('switch/notify_low-immediate-and-reversible', 'open=notifications', r'''()=>{const sel='[data-key="notify_low"][role="switch"]',real=NXDemo.call;NXDemo.call=(m,...a)=>m==='set_preferences'?new Promise(()=>{}):real(m,...a);const before=document.querySelector(sel).getAttribute('aria-checked');document.querySelector(sel).click();const now=document.querySelector(sel),one=now.getAttribute('aria-checked')!==before&&!now.disabled&&!now.hasAttribute('aria-busy');now.click();return one&&document.querySelector(sel).getAttribute('aria-checked')===before&&!document.querySelector(sel).querySelector('.control-feedback');}'''),
('switch/no-backend-spinner-while-pending', 'open=automation&scenario=preference-pending', r'''async()=>{const b=document.querySelector('[data-key="task_continuation"]');b.click();await new Promise(r=>setTimeout(r,60));const n=document.querySelector('[data-key="task_continuation"]');return !n.disabled&&!n.hasAttribute('aria-busy')&&n.getAttribute('aria-checked')==='false';}'''),
('switch/rollback-latest-failure', 'open=settings&scenario=preference-failed', r'''async()=>{const s='[data-key="autostart"]',before=document.querySelector(s).getAttribute('aria-checked');document.querySelector(s).click();if(document.querySelector(s).getAttribute('aria-checked')===before)return false;await new Promise(r=>setTimeout(r,80));return document.querySelector(s).getAttribute('aria-checked')===before&&!document.querySelector(s).disabled&&!!document.querySelector('.status-notification');}'''),
('switch/independent-account-changes-persist', 'open=relay-accounts', r'''async()=>{const a=[...document.querySelectorAll('.relay-account-row .switch')].slice(0,2).map(n=>n.dataset.email);for(const e of a)document.querySelector(`[data-action="auto-relay-account"][data-email="${e}"]`).click();await new Promise(r=>setTimeout(r,80));await NXPreview.refresh();return a.every(e=>NXDemo.state().settings.auto_relay_excluded.includes(e)&&document.querySelector(`[data-email="${e}"].switch`).getAttribute('aria-checked')==='false');}'''),
('switch/late-snapshot-does-not-revert-click', 'open=settings', r'''async()=>{const real=NXDemo.call;let release;NXDemo.call=(m,...a)=>m==='set_preferences'?new Promise(r=>release=()=>real(m,...a).then(r)):real(m,...a);document.querySelector('[data-key="autostart"]').click();await new Promise(r=>setTimeout(r,10));await NXPreview.refresh();if(document.querySelector('[data-key="autostart"]').getAttribute('aria-checked')!=='true')return false;release();await new Promise(r=>setTimeout(r,50));return NXDemo.state().settings.autostart===true;}'''),
('shapes/nested-radius-matches-inset', 'open=settings&case=appearance-expanded', r'''()=>{const outer=document.querySelector('[data-disclosure="appearance"] .segmented'),inner=outer.querySelector('.active'),a=getComputedStyle(outer),b=getComputedStyle(inner);return (outer.getBoundingClientRect().height-inner.getBoundingClientRect().height)/2===parseFloat(a.paddingTop)&&a.borderRadius==='999px'&&b.borderRadius==='999px';}'''),
('expiry/plain-text-and-stable-actions', 'open=detail&scenario=member-none', r'''async()=>{const n=document.querySelector('.detail-expiry-note'),y=document.querySelector('.danger-row').getBoundingClientRect().top;n.click();if(NXPreview.info().page!=='detail'||n.tagName!=='DIV')return false;document.querySelector('.account-editor summary').click();document.querySelector('#manual-date').value='2027-01-11';document.querySelector('[data-action="save-expiry"]').click();await new Promise(r=>setTimeout(r,80));document.querySelector('.account-editor summary').click();return document.querySelector('.detail-expiry-note').textContent.includes('2027/01/11')&&document.querySelector('.danger-row').getBoundingClientRect().top===y;}'''),
('inline/relay-opens-without-third-level', 'open=automation', r'''async()=>{const s='[data-disclosure="relay"]';document.querySelector(s+' > summary').click();await new Promise(r=>setTimeout(r,60));const good=NXPreview.info().page==='settings'&&document.querySelector(s).open;document.querySelector(s+' > summary').click();await new Promise(r=>setTimeout(r,20));return good&&!document.querySelector(s).open;}'''),
('inline/message-opens-without-third-level', 'open=automation', r'''async()=>{const s='[data-disclosure="message"]';document.querySelector(s+' > summary').click();await new Promise(r=>setTimeout(r,60));const good=NXPreview.info().page==='settings'&&document.querySelector(s).open;document.querySelector(s+' > summary').click();await new Promise(r=>setTimeout(r,20));return good&&!document.querySelector(s).open;}'''),
('history/independent-page-from-settings', 'open=automation', r'''async()=>{document.querySelector('[data-action="resume-details"]').click();await new Promise(r=>setTimeout(r,70));return NXPreview.info().page==='resume'&&!document.querySelector('[data-disclosure="resume"]');}'''),
('inline/hotkeys-and-archives-stay-settings', 'open=settings&scenario=archived', r'''async()=>{for(const k of ['hotkeys','archives']){document.querySelector(`[data-disclosure="${k}"] > summary`).click();await new Promise(r=>setTimeout(r,50));}return NXPreview.info().page==='settings'&&document.querySelectorAll('.settings-disclosure[open]').length===1&&document.querySelector('[data-disclosure=archives]').open&&document.querySelectorAll('.archive-row').length===1&&document.querySelectorAll('.hotkey-row').length===5;}'''),
('inline/long-roster-eight-plus-remainder', 'open=automation&scenario=many', r'''async()=>{document.querySelector('[data-disclosure="relay"] > summary').click();await new Promise(r=>setTimeout(r,20));if(document.querySelectorAll('.relay-account-row').length!==8)return false;document.querySelector('[data-action="collection-more"]').click();const n=document.querySelectorAll('.relay-account-row').length;document.querySelector('[data-action="collection-more"]').click();return n===14&&document.querySelectorAll('.relay-account-row').length===8&&NXPreview.info().page==='settings';}'''),
('inline/message-survives-refresh-switch-and-collapse', 'open=automation', r'''async()=>{const sel='[data-disclosure="message"] > summary';document.querySelector(sel).click();await new Promise(r=>setTimeout(r,20));const f=document.querySelector('#resume-message');f.value='未保存的消息';f.dispatchEvent(new Event('input',{bubbles:true}));f.focus();f.setSelectionRange(2,4);document.querySelector('[data-key="auto_relay"]').click();await NXPreview.refresh();if(document.querySelector('#resume-message').value!=='未保存的消息')return false;document.querySelector(sel).click();await new Promise(r=>setTimeout(r,10));document.querySelector(sel).click();await new Promise(r=>setTimeout(r,20));return document.querySelector('#resume-message').value==='未保存的消息';}'''),
('inline/save-failure-visible-and-input-retry-clears', 'open=automation&scenario=preference-failed', r'''async()=>{document.querySelector('[data-disclosure="message"] > summary').click();await new Promise(r=>setTimeout(r,15));const field=document.querySelector('#resume-message');field.value='继续这里';field.dispatchEvent(new Event('input',{bubbles:true}));document.querySelector('[data-action="save-resume-message"]').click();await new Promise(r=>setTimeout(r,100));await NXPreview.refresh();if(!document.querySelector('#form-error').textContent||document.querySelector('#resume-message').value!=='继续这里')return false;document.querySelector('#resume-message').value="继续";document.querySelector('#resume-message').dispatchEvent(new Event("input",{bubbles:true}));return !document.querySelector('#form-error').textContent&&document.querySelector('#resume-message').value==='继续';}'''),
('inline/archive-load-focus-and-collapse-survive', 'open=settings&scenario=archived', r'''async()=>{const s='[data-disclosure="archives"] > summary';document.querySelector(s).focus();document.querySelector(s).click();await new Promise(r=>setTimeout(r,80));const good=document.activeElement===document.querySelector(s);document.querySelector(s).click();await new Promise(r=>setTimeout(r,20));return good&&!document.querySelector('[data-disclosure="archives"]').open;}'''),
('inline/failed-lazy-read-does-not-loop-and-can-retry', 'open=settings', r'''async()=>{const real=NXDemo.call;let count=0;NXDemo.call=(m,...a)=>m==='get_archives'&&++count===1?Promise.reject(new Error('read failed')):real(m,...a);document.querySelector('[data-disclosure="archives"] > summary').click();await new Promise(r=>setTimeout(r,60));if(count!==1||!document.querySelector('[data-action="inline-reload"]'))return false;document.querySelector('[data-action="inline-reload"]').click();await new Promise(r=>setTimeout(r,80));return count===2&&!document.querySelector('[data-action="inline-reload"]')&&NXPreview.info().page==='settings';}'''),
('inline/late-archive-load-does-not-navigate-new-page', 'open=settings', r'''async()=>{const real=NXDemo.call;let release;NXDemo.call=(m,...a)=>m==='get_archives'?new Promise(r=>release=r):real(m,...a);document.querySelector('[data-disclosure="archives"] > summary').click();await new Promise(r=>setTimeout(r,15));document.querySelector('#sheet [data-action="back"]').click();await NXPreview.open(new URLSearchParams('open=edit'));document.querySelector('#alias').value='保留当前编辑';release([]);await new Promise(r=>setTimeout(r,50));return NXPreview.info().page==='detail'&&document.querySelector('#alias').value==='保留当前编辑';}'''),
('resume/bridge-ambiguity-is-visible-failure', 'open=resume&scenario=resume-bridge-ambiguous', r'''()=>{const s=document.querySelector('.sheet-body');return s.textContent.includes('存在多个桌面桥接')&&!s.textContent.includes('输入框')&&!!s.querySelector('[data-action="retry-resume-task"]')&&!!s.querySelector('.resume-zero');}'''),
('resume/bridge-ambiguity-home-error', 'scenario=resume-bridge-ambiguous', r'''()=>document.querySelector('.resume-notice').textContent.includes('失败')&&document.querySelector('.resume-notice').classList.contains('error')'''),
]

def main(browser,output):
 results=[]
 with browser_session(browser) as engine:
  for palette in ['light','dark']:
   for name,query,script in CASES:
    context=engine.new_context(viewport={'width':520,'height':700},reduced_motion='reduce',color_scheme=palette);page=context.new_page();errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
    try:
     page.set_content(demo_html(query+'&appearance='+palette));page.wait_for_function('window.NX_CASE_READY',timeout=5000);passed=page.evaluate("() => Promise.race([Promise.resolve().then(() => ("+script+")()),new Promise((_,reject)=>setTimeout(()=>reject(new Error('Behavior assertion timed out')),4000))])") is True
    except Exception as e:errors.append(str(e));passed=False
    results.append({'name':name,'appearance':palette,'passed':passed and not errors,'errors':errors});context.close()
   for scale in [1,1.25,1.5,2]:
    context=engine.new_context(viewport={'width':520,'height':700},device_scale_factor=scale,color_scheme=palette);p=context.new_page();p.set_content(demo_html('open=relay-accounts&appearance='+palette));p.wait_for_function('window.NX_CASE_READY')
    passed=p.evaluate('''()=>[...document.querySelectorAll('.switch')].every(s=>{const r=s.getBoundingClientRect(),k=s.querySelector('i').getBoundingClientRect();return Math.abs((r.top+r.bottom-k.top-k.bottom)/2)<.25&&k.top>=r.top+2.5&&k.bottom<=r.bottom-2.5;})''')
    results.append({'name':f'geometry/knob-centered-dpr-{scale}','appearance':palette,'passed':passed,'errors':[]});context.close()
 output.parent.mkdir(parents=True,exist_ok=True);output.write_text(json.dumps(results,ensure_ascii=False,indent=2));print('Settings UX:',sum(r['passed'] for r in results),'/',len(results))
 for r in results:
  if not r['passed']:print(r)
 return int(any(not r['passed'] for r in results))
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--browser',required=True,type=Path);p.add_argument('--output',type=Path,default=ROOT/'docs/validation/ui-settings-tests.json');a=p.parse_args();raise SystemExit(main(a.browser,a.output))
