"""Regression cases for maintained product flows; removed compact/manual-message UI retired in 5.7.5."""
from __future__ import annotations
import argparse,json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT/'tools'))
from browser_session import browser_session,demo_html

CASES = [
('dock/home-no-layout-shift', '', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms)),rect=n=>(typeof n==='string'?$(n):n).getBoundingClientRect(),start=async()=>{NXDemo.simulate('start-resume');await NXPreview.refresh();await sleep(25);},near=(a,b)=>Math.abs(a-b)<1;const selectors=[".current-card", ".relay", ".account-list", ".footer"];const before=selectors.map(s=>rect(s).toJSON());await start();const after=selectors.map(s=>rect(s).toJSON());if(JSON.stringify(before)!==JSON.stringify(after))return false;NXDemo.simulate('clear-status');await NXPreview.refresh();return JSON.stringify(before)===JSON.stringify(selectors.map(s=>rect(s).toJSON()));}'''),
('dock/home-third-slot-and-footer-hit-test', '', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms)),rect=n=>(typeof n==='string'?$(n):n).getBoundingClientRect(),start=async()=>{NXDemo.simulate('start-resume');await NXPreview.refresh();await sleep(25);},near=(a,b)=>Math.abs(a-b)<1;await start();const d=rect('.status-dock'),f=rect('.footer'),s=$('.status-dock');return near(d.height,40)&&near((d.top+d.bottom)/2,(rect('.account-list > .row:nth-child(3) .avatar').top+rect('.account-list > .row:nth-child(3) .avatar').bottom)/2)&&s.parentElement.id==='home'&&getComputedStyle(s).position==='absolute'&&$('.footer').contains(document.elementFromPoint(f.x+f.width/2,f.y+f.height/2));}'''),
('dock/home-last-row-scrolls-clear', '', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms)),rect=n=>(typeof n==='string'?$(n):n).getBoundingClientRect(),start=async()=>{NXDemo.simulate('start-resume');await NXPreview.refresh();await sleep(25);},near=(a,b)=>Math.abs(a-b)<1;await start();const viewport=$('.account-list');viewport.scrollTop=viewport.scrollHeight;await sleep(30);const row=viewport.querySelector('.row:last-of-type'),r=rect(row),d=rect('.status-dock');return r.bottom<=d.top&&row.contains(document.elementFromPoint(r.x+20,r.y+r.height/2));}'''),
('dock/home-dismiss-keeps-scroll', '', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms)),rect=n=>(typeof n==='string'?$(n):n).getBoundingClientRect(),start=async()=>{NXDemo.simulate('start-resume');await NXPreview.refresh();await sleep(25);},near=(a,b)=>Math.abs(a-b)<1;await start();const viewport=$('.account-list');viewport.scrollTop=viewport.scrollHeight;await sleep(20);const before=viewport.scrollTop;$('[data-action=dismiss-status]').click();await sleep(20);return $('.status-dock').hidden&&near(viewport.scrollTop,before)&&!!NXDemo.state().resume;}'''),
('dock/status-once-inside-modal', 'open=settings', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms)),rect=n=>(typeof n==='string'?$(n):n).getBoundingClientRect(),start=async()=>{NXDemo.simulate('start-resume');await NXPreview.refresh();await sleep(25);},near=(a,b)=>Math.abs(a-b)<1;await start();return document.querySelectorAll('.status-dock').length===1&&$('.status-dock').parentElement.id==='sheet'&&!$('#home .status-dock')&&$('.status-dock .status-text').textContent.includes('接续');}'''),
('dock/settings-default-positions-stable', 'open=settings', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms)),rect=n=>(typeof n==='string'?$(n):n).getBoundingClientRect(),start=async()=>{NXDemo.simulate('start-resume');await NXPreview.refresh();await sleep(25);},near=(a,b)=>Math.abs(a-b)<1;const before=[...document.querySelectorAll('.settings-heading,.settings-list > *')].map(n=>rect(n).toJSON());await start();return JSON.stringify(before)===JSON.stringify([...document.querySelectorAll('.settings-heading,.settings-list > *')].map(n=>rect(n).toJSON()));}'''),
('dock/expansion-rebases-scroll-tail-before-poll', 'open=settings&scenario=resume-progress', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms)),rect=n=>(typeof n==='string'?$(n):n).getBoundingClientRect(),start=async()=>{NXDemo.simulate('start-resume');await NXPreview.refresh();await sleep(25);},near=(a,b)=>Math.abs(a-b)<1;$('[data-disclosure=notifications] > summary').click();$('[data-disclosure=relay] > summary').click();await sleep(35);const v=$('.sheet-body');v.scrollTop=v.scrollHeight;const r=rect('[data-disclosure=archives]'),d=rect('.status-dock');return r.bottom<=d.top-7&&$('[data-disclosure=archives]').contains(document.elementFromPoint(r.x+25,r.top+r.height/2));}'''),
('dock/collapse-then-expand-retains-reachable-tail', 'open=settings&scenario=resume-progress', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms)),rect=n=>(typeof n==='string'?$(n):n).getBoundingClientRect(),start=async()=>{NXDemo.simulate('start-resume');await NXPreview.refresh();await sleep(25);},near=(a,b)=>Math.abs(a-b)<1;const summary=$('[data-disclosure=relay] > summary');for(let i=0;i<3;i++){summary.click();await sleep(10);}const v=$('.sheet-body');v.scrollTop=v.scrollHeight;const r=rect('[data-disclosure=archives]'),d=rect('.status-dock');return r.bottom<=d.top-7&&document.querySelectorAll('.status-runway').length===1;}'''),
('dock/detail-footer-date-static', 'open=detail&scenario=member-none', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms)),rect=n=>(typeof n==='string'?$(n):n).getBoundingClientRect(),start=async()=>{NXDemo.simulate('start-resume');await NXPreview.refresh();await sleep(25);},near=(a,b)=>Math.abs(a-b)<1;const before=rect('.detail-footer').toJSON(),date=rect('.detail-expiry-note').toJSON();await start();return JSON.stringify(before)===JSON.stringify(rect('.detail-footer').toJSON())&&JSON.stringify(date)===JSON.stringify(rect('.detail-expiry-note').toJSON())&&near(rect('#app').bottom-rect('.status-dock').bottom,12);}'''),
('dock/detail-edit-focus-can-clear-status', 'open=edit', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms)),rect=n=>(typeof n==='string'?$(n):n).getBoundingClientRect(),start=async()=>{NXDemo.simulate('start-resume');await NXPreview.refresh();await sleep(25);},near=(a,b)=>Math.abs(a-b)<1;await start();const v=$('.sheet-body');v.scrollTop=0;$('#manual-date').focus();await sleep(30);const r=rect('#manual-date'),d=rect('.status-dock');return r.bottom<=d.top-7&&document.activeElement.id==='manual-date';}'''),
('dock/detail-footer-never-scrolls-with-content', 'open=edit', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms)),rect=n=>(typeof n==='string'?$(n):n).getBoundingClientRect(),start=async()=>{NXDemo.simulate('start-resume');await NXPreview.refresh();await sleep(25);},near=(a,b)=>Math.abs(a-b)<1;const y=rect('.detail-footer').top;$('.sheet-body').scrollTop=999;return rect('.detail-footer').top===y&&$('.sheet-body').scrollTop>0;}'''),
('dock/dismiss-preserves-record-and-stays-dismissed', 'scenario=resume-failed', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms)),rect=n=>(typeof n==='string'?$(n):n).getBoundingClientRect(),start=async()=>{NXDemo.simulate('start-resume');await NXPreview.refresh();await sleep(25);},near=(a,b)=>Math.abs(a-b)<1;const state=JSON.stringify(NXDemo.state().resume);$('[data-action=dismiss-status]').click();await NXPreview.refresh();return $('.status-dock').hidden&&JSON.stringify(NXDemo.state().resume)===state;}'''),
('dock/new-state-reappears-after-dismiss', 'scenario=resume-progress', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms)),rect=n=>(typeof n==='string'?$(n):n).getBoundingClientRect(),start=async()=>{NXDemo.simulate('start-resume');await NXPreview.refresh();await sleep(25);},near=(a,b)=>Math.abs(a-b)<1;$('[data-action=dismiss-status]').click();NXDemo.simulate('complete-resume');await NXPreview.refresh();return !$('.status-dock').hidden&&$('.status-bar').classList.contains('success');}'''),
('dock/notice-read-navigates-to-history', 'scenario=resume-failed', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms)),rect=n=>(typeof n==='string'?$(n):n).getBoundingClientRect(),start=async()=>{NXDemo.simulate('start-resume');await NXPreview.refresh();await sleep(25);},near=(a,b)=>Math.abs(a-b)<1;$('.status-dock [data-action=resume-details]').click();await sleep(100);return NXPreview.info().page==='resume'&&$('.status-dock').hidden;}'''),
('dock/onboarding-one-status-above-actions', 'scenario=empty', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms)),rect=n=>(typeof n==='string'?$(n):n).getBoundingClientRect(),start=async()=>{NXDemo.simulate('start-resume');await NXPreview.refresh();await sleep(25);},near=(a,b)=>Math.abs(a-b)<1;return document.querySelectorAll('.status-bar').length===1&&near(rect('.onboarding-foot').top-rect('.status-dock').bottom,8)&&!$('.onboarding-main .status-bar');}'''),
('dock/confirm-status-above-actions', 'open=confirm&scenario=resume-progress', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms)),rect=n=>(typeof n==='string'?$(n):n).getBoundingClientRect(),start=async()=>{NXDemo.simulate('start-resume');await NXPreview.refresh();await sleep(25);},near=(a,b)=>Math.abs(a-b)<1;return near(rect('.sheet-foot').top-rect('.status-dock').bottom,8)&&!$('.sheet-body .status-bar');}'''),
('dock/has-distinct-surface-and-shadow', 'scenario=resume-failed', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms)),rect=n=>(typeof n==='string'?$(n):n).getBoundingClientRect(),start=async()=>{NXDemo.simulate('start-resume');await NXPreview.refresh();await sleep(25);},near=(a,b)=>Math.abs(a-b)<1;const c=getComputedStyle($('.status-notification')),bg=getComputedStyle($('#app')).backgroundColor;return c.boxShadow!=='none'&&c.borderTopWidth==='1px'&&c.backgroundColor!==getComputedStyle($('.status-bar')).backgroundColor&&getComputedStyle($('.status-dock')).pointerEvents==='none'&&c.pointerEvents==='auto';}'''),
('dock/no-foreground-tooltip-collision', 'open=usage&scenario=resume-progress', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms)),rect=n=>(typeof n==='string'?$(n):n).getBoundingClientRect(),start=async()=>{NXDemo.simulate('start-resume');await NXPreview.refresh();await sleep(25);},near=(a,b)=>Math.abs(a-b)<1;const bar=$('.trend-bar');bar.focus();await sleep(35);return getComputedStyle($('#float-tip')).zIndex>getComputedStyle($('.status-dock')).zIndex;}'''),
('usage/two-flat-regions-no-background-cards', 'open=usage', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms)),rect=n=>(typeof n==='string'?$(n):n).getBoundingClientRect(),start=async()=>{NXDemo.simulate('start-resume');await NXPreview.refresh();await sleep(25);},near=(a,b)=>Math.abs(a-b)<1;const cards=[...document.querySelectorAll('.usage-body > .usage-context,.usage-body > .usage-summary')];return document.querySelectorAll('.usage-body > .card').length===0&&cards.length===2&&cards[0].contains($('.usage-top'))&&cards[0].contains($('.usage-filter'))&&cards[1].contains($('.usage-total'))&&cards[1].contains($('.usage-trend'))&&!cards.some(n=>n.contains($('.usage-accounts')))&&getComputedStyle($('.usage-accounts')).backgroundColor==='rgba(0, 0, 0, 0)';}'''),
('usage/time-switch-retains-head-geometry', 'open=usage', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms)),rect=n=>(typeof n==='string'?$(n):n).getBoundingClientRect(),start=async()=>{NXDemo.simulate('start-resume');await NXPreview.refresh();await sleep(25);},near=(a,b)=>Math.abs(a-b)<1;const r=rect('.usage-context').toJSON();for(const value of ['7','180','all','30']){$('[data-action=usage-period][data-value="'+value+'"]').click();await sleep(35);if(JSON.stringify(rect('.usage-context').toJSON())!==JSON.stringify(r))return false;}return true;}'''),
('usage/account-avatar-is-shared', 'open=usage&email=work-01@example.com', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms)),rect=n=>(typeof n==='string'?$(n):n).getBoundingClientRect(),start=async()=>{NXDemo.simulate('start-resume');await NXPreview.refresh();await sleep(25);},near=(a,b)=>Math.abs(a-b)<1;return rect('.usage-top .avatar').width===40&&$('.usage-top .identity').textContent.includes('工作 01')&&$('.usage-top .badge').textContent==='Plus';}'''),
('usage/aggregate-uses-brand-not-letter-avatar', 'open=usage', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms)),rect=n=>(typeof n==='string'?$(n):n).getBoundingClientRect(),start=async()=>{NXDemo.simulate('start-resume');await NXPreview.refresh();await sleep(25);},near=(a,b)=>Math.abs(a-b)<1;return !!$('.usage-top .mark svg')&&!$('.usage-top .avatar')&&rect('.usage-top .mark').width===40;}'''),
('usage/single-7-fits', 'open=usage&email=work-01@example.com&days=7', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms)),rect=n=>(typeof n==='string'?$(n):n).getBoundingClientRect(),start=async()=>{NXDemo.simulate('start-resume');await NXPreview.refresh();await sleep(25);},near=(a,b)=>Math.abs(a-b)<1;const b=$('.sheet-body');return b.scrollHeight-b.clientHeight<=60&&!!$('.usage-bottom-back')&&!!$('.usage-account-details .metrics-row');}'''),
('usage/single-30-fits', 'open=usage&email=work-01@example.com&days=30', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms)),rect=n=>(typeof n==='string'?$(n):n).getBoundingClientRect(),start=async()=>{NXDemo.simulate('start-resume');await NXPreview.refresh();await sleep(25);},near=(a,b)=>Math.abs(a-b)<1;const b=$('.sheet-body');return b.scrollHeight-b.clientHeight<=60&&!!$('.usage-bottom-back')&&!!$('.usage-account-details .metrics-row');}'''),
('usage/single-180-fits', 'open=usage&email=work-01@example.com&days=180', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms)),rect=n=>(typeof n==='string'?$(n):n).getBoundingClientRect(),start=async()=>{NXDemo.simulate('start-resume');await NXPreview.refresh();await sleep(25);},near=(a,b)=>Math.abs(a-b)<1;const b=$('.sheet-body');return b.scrollHeight-b.clientHeight<=60&&!!$('.usage-bottom-back')&&!!$('.usage-account-details .metrics-row');}'''),
('usage/single-all-fits', 'open=usage&email=work-01@example.com&days=all', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms)),rect=n=>(typeof n==='string'?$(n):n).getBoundingClientRect(),start=async()=>{NXDemo.simulate('start-resume');await NXPreview.refresh();await sleep(25);},near=(a,b)=>Math.abs(a-b)<1;const b=$('.sheet-body');return b.scrollHeight-b.clientHeight<=60&&!!$('.usage-bottom-back')&&!!$('.usage-account-details .metrics-row');}'''),
('usage/long-account-name-does-not-push-refresh', 'open=usage&email=work-01@example.com&scenario=long-names', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms)),rect=n=>(typeof n==='string'?$(n):n).getBoundingClientRect(),start=async()=>{NXDemo.simulate('start-resume');await NXPreview.refresh();await sleep(25);},near=(a,b)=>Math.abs(a-b)<1;const b=rect('.usage-context'),r=rect('.usage-top .tool');return r.right<=b.right-10&&$('.usage-top .identity-copy strong').scrollWidth>$('.usage-top .identity-copy strong').clientWidth;}'''),
('usage/unknown-account-recovers-overview', 'open=usage&email=removed@example.com', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms)),rect=n=>(typeof n==='string'?$(n):n).getBoundingClientRect(),start=async()=>{NXDemo.simulate('start-resume');await NXPreview.refresh();await sleep(25);},near=(a,b)=>Math.abs(a-b)<1;return !!$('.usage-context')&&!!$('.usage-accounts')&&!$('.usage-body > .empty');}'''),
('identity/avatar-scale-home-and-list', '', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms)),rect=n=>(typeof n==='string'?$(n):n).getBoundingClientRect(),start=async()=>{NXDemo.simulate('start-resume');await NXPreview.refresh();await sleep(25);},near=(a,b)=>Math.abs(a-b)<1;return rect('.current-card .avatar').width===40&&[...document.querySelectorAll('.row .avatar')].every(n=>rect(n).width===36);}'''),
('identity/global-brand-single-svg-source', '', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms)),rect=n=>(typeof n==='string'?$(n):n).getBoundingClientRect(),start=async()=>{NXDemo.simulate('start-resume');await NXPreview.refresh();await sleep(25);},near=(a,b)=>Math.abs(a-b)<1;const shape=$('.mark svg').outerHTML;await NXPreview.open(new URLSearchParams('open=usage'));return $('.usage-top .mark svg').outerHTML===shape&&$('.mark').getAttribute('aria-label')==='n×';}'''),
('empty/status-does-not-move-centered-text', 'scenario=single-account', r'''async()=>{const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms)),rect=n=>(typeof n==='string'?$(n):n).getBoundingClientRect(),start=async()=>{NXDemo.simulate('start-resume');await NXPreview.refresh();await sleep(25);},near=(a,b)=>Math.abs(a-b)<1;const before=rect('.roster-empty span').toJSON();await start();return JSON.stringify(before)===JSON.stringify(rect('.roster-empty span').toJSON());}'''),
]

def main(browser,output):
 results=[]
 with browser_session(browser) as engine:
  for palette in ('light','dark'):
   for name,q,script in CASES:
    ctx=engine.new_context(viewport={'width':520,'height':700},color_scheme=palette,reduced_motion='reduce');p=ctx.new_page();errors=[];p.on('pageerror',lambda e:errors.append(str(e)))
    try:
     p.set_content(demo_html(q+'&appearance='+palette));p.wait_for_function('window.NX_CASE_READY',timeout=6000);passed=p.evaluate(script) is True
    except Exception as e:errors.append(str(e));passed=False
    results.append({'name':name,'appearance':palette,'passed':passed and not errors,'errors':errors});ctx.close()
 output.parent.mkdir(parents=True,exist_ok=True);output.write_text(json.dumps(results,ensure_ascii=False,indent=2));print('Shared surfaces:',sum(r['passed'] for r in results),'/',len(results))
 for r in results:
  if not r['passed']:print(r)
 return int(any(not r['passed'] for r in results))
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--browser',required=True,type=Path);p.add_argument('--output',type=Path,default=ROOT/'docs/validation/ui-surfaces-tests.json');a=p.parse_args();raise SystemExit(main(a.browser,a.output))
